//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookPool.DataObjects.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableBook
    {
        public int ID { get; set; }
        public string BookName { get; set; }
        public decimal Price { get; set; }
        public int BookConditionID { get; set; }
        public int BookLanguageID { get; set; }
        public bool Academic { get; set; }
        public int CategoryID { get; set; }
        public string GoogleID { get; set; }
        public string OwnerUserID { get; set; }
        public string SellingStatus { get; set; }
    }
}
