//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookPool.DataObjects.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public int OrderHeaderID { get; set; }
        public string BookName { get; set; }
        public string BookImage { get; set; }
        public decimal BookPrice { get; set; }
        public string Status { get; set; }
        public string SellerUserID { get; set; }
        public string Authors { get; set; }
        public string GoogleID { get; set; }
        public int BookID { get; set; }
    }
}
